CREATE TABLE IF NOT EXISTS rules (
    id SERIAL PRIMARY KEY,
    norder INT NOT NULL,
    allow BOOLEAN NOT NULL,
    ip_address VARCHAR,
    protocol VARCHAR,
    fqdn VARCHAR,
    path VARCHAR,
    query VARCHAR,
    city_name VARCHAR,
    country_name VARCHAR,
    country_code VARCHAR,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
