export default interface Rule {
    id: number;
    name: string;
    description: string;
    mode: string;
    weight?: number;
    allow?: boolean;
    store?: boolean;
    pipeline?: string;
    ip_address?: string;
    protocol?: string;
    fqdn?: string;
    path?: string;
    query?: string;
    city_name?: string;
    country_name?: string;
    country_code?: string;
    user_agent?: string;
    method?: string;
    referer?: string;
    content_type?: string;
    accept_language?: string;
    x_request_id?: string;
    rate_limit_profile_id?: number;
    rate_limit_profile_name?: string;
    active?: number;
    created_at?: Date;
    updated_at?: Date;
}