//! # Plantillas de reglas preconfiguradas
//!
//! Catálogo de reglas recomendadas para servicios populares.
//! Los usuarios pueden aplicar estas plantillas desde el frontend.

use serde::Serialize;

/// A preconfigured rule template.
#[derive(Debug, Serialize, Clone)]
pub struct RuleTemplate {
    pub name: String,
    pub description: String,
    pub category: String,
    pub severity: String, // "🔥 Crítico", "🔴 Alto", "🟡 Medio", "🟢 Bajo"
    pub path: Option<String>,
    pub query: Option<String>,
    pub country_code: Option<String>,
    pub allow: bool,
    pub store: bool,
    pub rate_limit_enabled: bool,
    pub max_retry: Option<i32>,
    pub find_time_seconds: Option<i64>,
    pub ban_time_seconds: Option<i64>,
    pub bantime_increment: bool,
    pub bantime_multipliers: Vec<i32>,
    pub bantime_maxtime_seconds: i64,
    pub ban_count_decay_days: i32,
}

/// All available templates, grouped by category.
pub fn all_templates() -> Vec<RuleTemplate> {
    vec![
        // ── WordPress ──
        RuleTemplate {
            name: "WordPress - wp-login".into(),
            description: "Protege el login de WordPress contra fuerza bruta".into(),
            category: "wordpress".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/wp-login\.php".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
        },
        RuleTemplate {
            name: "WordPress - xmlrpc".into(),
            description: "xmlrpc.php es vector clásico de fuerza bruta y DDoS".into(),
            category: "wordpress".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/xmlrpc\.php".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
        },
        RuleTemplate {
            name: "WordPress - wp-admin".into(),
            description: "Protege el panel de administración de WordPress".into(),
            category: "wordpress".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/wp-admin".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(10),
            find_time_seconds: Some(1800),
            ban_time_seconds: Some(7200),
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 7200,
            ban_count_decay_days: 30,
        },
        // ── phpMyAdmin ──
        RuleTemplate {
            name: "phpMyAdmin - login".into(),
            description: "Protege phpMyAdmin contra accesos no autorizados".into(),
            category: "paneles".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(phpmyadmin|pma|mysql|phpPgAdmin)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
        },
        // ── API Auth ──
        RuleTemplate {
            name: "API - login endpoint".into(),
            description: "Protege endpoints de autenticación contra fuerza bruta".into(),
            category: "api".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/(api|auth)/(login|signin|token)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
        },
        RuleTemplate {
            name: "API - register endpoint".into(),
            description: "Protege registros contra bots".into(),
            category: "api".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/(api|auth)/(register|signup)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(3600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
        },
        // ── Seguridad general ──
        RuleTemplate {
            name: "Archivos sensibles".into(),
            description: "Bloquea acceso a archivos de configuración y backups".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"\.(env|bak|sql|dump|config|yml|yaml|json|log|ini)$".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
        },
        RuleTemplate {
            name: "Directorios de sistema".into(),
            description: "Bloquea acceso a directorios internos del proyecto".into(),
            category: "seguridad".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(vendor|node_modules|storage|cache|logs|tmp|\.git|\.env)".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
        },
        // ── Geo ──
        RuleTemplate {
            name: "Bloquear países sin negocio".into(),
            description: "Deniega tráfico de países donde no operas".into(),
            category: "geo".into(),
            severity: "🟢 Bajo".into(),
            path: None,
            query: None,
            country_code: Some(r"^(RU|CN|KP|IR)$".into()),
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
        },
    ]
}