//! # Plantillas de reglas preconfiguradas
//!
//! Catálogo de reglas recomendadas para servicios populares.
//! Los usuarios pueden aplicar estas plantillas desde el frontend.

use serde::Serialize;

/// A preconfigured rule template.
#[derive(Debug, Serialize, Clone)]
pub struct RuleTemplate {
    pub name: String,
    pub description: String,
    pub category: String,
    pub severity: String, // "🔥 Crítico", "🔴 Alto", "🟡 Medio", "🟢 Bajo"
    pub path: Option<String>,
    pub query: Option<String>,
    pub country_code: Option<String>,
    pub allow: bool,
    pub store: bool,
    pub rate_limit_enabled: bool,
    pub max_retry: Option<i32>,
    pub find_time_seconds: Option<i32>,
    pub ban_time_seconds: Option<i32>,
    pub bantime_increment: bool,
    pub bantime_multipliers: Vec<i32>,
    pub bantime_maxtime_seconds: i32,
    pub ban_count_decay_days: i32,
    pub requires_fqdn: bool,
}

/// All available templates, grouped by category.
pub fn all_templates() -> Vec<RuleTemplate> {
    vec![
        // ════════════════════════════════════════════
        // WordPress
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "WordPress - wp-login".into(),
            description: "Protege el login de WordPress contra fuerza bruta".into(),
            category: "wordpress".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/wp-login\.php".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "WordPress - xmlrpc".into(),
            description: "xmlrpc.php es vector clásico de fuerza bruta y DDoS".into(),
            category: "wordpress".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/xmlrpc\.php".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "WordPress - wp-admin".into(),
            description: "Protege el panel de administración de WordPress".into(),
            category: "wordpress".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/wp-admin".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(10),
            find_time_seconds: Some(1800),
            ban_time_seconds: Some(7200),
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 7200,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "WordPress - REST API".into(),
            description: "Protege la API REST de WordPress contra abusos".into(),
            category: "wordpress".into(),
            severity: "🟡 Medio".into(),
            path: Some(r"^/wp-json/".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(30),
            find_time_seconds: Some(300),
            ban_time_seconds: Some(1800),
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "WordPress - wp-content uploads".into(),
            description: "Bloquea ejecución de scripts en directorio de uploads".into(),
            category: "wordpress".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/wp-content/uploads/.*\.(php|phtml|php5)$".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },

        // ════════════════════════════════════════════
        // Joomla
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "Joomla - administrator".into(),
            description: "Protege el panel de administración de Joomla".into(),
            category: "joomla".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/administrator/".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Joomla - com_user".into(),
            description: "Protege el componente de usuarios de Joomla".into(),
            category: "joomla".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/index\.php\?option=com_users".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },

        // ════════════════════════════════════════════
        // Drupal
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "Drupal - user login".into(),
            description: "Protege el login de Drupal contra fuerza bruta".into(),
            category: "drupal".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(user|users?/login)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Drupal - install.php".into(),
            description: "Bloquea el instalador de Drupal (debe eliminarse tras instalar)".into(),
            category: "drupal".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/install\.php".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },

        // ════════════════════════════════════════════
        // Laravel
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "Laravel - debug bar".into(),
            description: "Bloquea la barra de depuración de Laravel en producción".into(),
            category: "laravel".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/_debugbar".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Laravel - Telescope".into(),
            description: "Bloquea Laravel Telescope en producción".into(),
            category: "laravel".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/telescope".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },

        // ════════════════════════════════════════════
        // Paneles de administración
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "phpMyAdmin - login".into(),
            description: "Protege phpMyAdmin contra accesos no autorizados".into(),
            category: "paneles".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(phpmyadmin|pma|mysql|phpPgAdmin)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "cPanel / WHM".into(),
            description: "Protege cPanel y Web Host Manager contra accesos".into(),
            category: "paneles".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(cpanel|whm|webmail|:2083|:2087)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Webmin / Usermin".into(),
            description: "Protege paneles Webmin y Usermin".into(),
            category: "paneles".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/(webmin|usermin)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Adminer".into(),
            description: "Bloquea Adminer (herramienta de gestión BD)".into(),
            category: "paneles".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(adminer|adminer-)".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },

        // ════════════════════════════════════════════
        // API
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "API - login endpoint".into(),
            description: "Protege endpoints de autenticación contra fuerza bruta".into(),
            category: "api".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/(api|auth)/(login|signin|token)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "API - register endpoint".into(),
            description: "Protege registros contra bots".into(),
            category: "api".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/(api|auth)/(register|signup)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(3600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "API - password reset".into(),
            description: "Protege endpoints de recuperación de contraseña".into(),
            category: "api".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/(api|auth)/(reset|forgot|recover)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(3600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "API - GraphQL introspection".into(),
            description: "Bloquea consultas de introspection de GraphQL en producción".into(),
            category: "api".into(),
            severity: "🟡 Medio".into(),
            path: Some(r"^/(graphql|api/graphql)".into()),
            query: Some(r"(__schema|__type)".into()),
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },

        // ════════════════════════════════════════════
        // Servidores de aplicaciones
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "Tomcat - manager".into(),
            description: "Protege el panel de gestión de Apache Tomcat".into(),
            category: "servidores".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(manager|host-manager)/".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Jenkins - login".into(),
            description: "Protege Jenkins contra fuerza bruta".into(),
            category: "servidores".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(jenkins|ci)/".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Git - .git exposure".into(),
            description: "Bloquea exposición del directorio .git".into(),
            category: "servidores".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/\.git".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },

        // ════════════════════════════════════════════
        // Seguridad general
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "Archivos sensibles".into(),
            description: "Bloquea acceso a archivos de configuración y backups".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"\.(env|bak|sql|dump|config|yml|yaml|json|log|ini)$".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "Directorios de sistema".into(),
            description: "Bloquea acceso a directorios internos del proyecto".into(),
            category: "seguridad".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(vendor|node_modules|storage|cache|logs|tmp|\.git|\.env)".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "Path traversal probes".into(),
            description: "Detecta intentos de path traversal (../)".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"\.\./".into()),
            query: Some(r"\.\./".into()),
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "SQL injection probes".into(),
            description: "Detecta patrones comunes de SQL injection".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            path: None,
            query: Some(r"(\bunion\b.*\bselect\b|'\s+or\s+|=|\bexec\b|\bxp_cmdshell\b)".into()),
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "XSS probes".into(),
            description: "Detecta patrones comunes de Cross-Site Scripting".into(),
            category: "seguridad".into(),
            severity: "🟡 Medio".into(),
            path: None,
            query: Some(r"(<script|<iframe|onerror=|onload=|javascript:)".into()),
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(10),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "phpinfo exposure".into(),
            description: "Bloquea phpinfo() que expone configuración del servidor".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"(phpinfo|info\.php)".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },

        // ════════════════════════════════════════════
        // Bots y scrapers
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "User-Agent bots conocidos".into(),
            description: "Bloquea user-agents de bots maliciosos conocidos".into(),
            category: "bots".into(),
            severity: "🟡 Medio".into(),
            path: None,
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "Rate limit - scraping".into(),
            description: "Rate limiting agresivo para prevenir scraping masivo".into(),
            category: "bots".into(),
            severity: "🟡 Medio".into(),
            path: None,
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(60),
            find_time_seconds: Some(60),
            ban_time_seconds: Some(600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 86400,
            ban_count_decay_days: 7,
            requires_fqdn: false,
        },

        // ════════════════════════════════════════════
        // Geo
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "Bloquear países sin negocio".into(),
            description: "Deniega tráfico de países donde no operas".into(),
            category: "geo".into(),
            severity: "🟢 Bajo".into(),
            path: None,
            query: None,
            country_code: Some(r"^(RU|CN|KP|IR)$".into()),
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "Bloquear tráfico hosting/VPS".into(),
            description: "Bloquea países con alta concentración de tráfico malicioso en hosting".into(),
            category: "geo".into(),
            severity: "🟢 Bajo".into(),
            path: None,
            query: None,
            country_code: Some(r"^(RU|CN|KP|IR|VN|UA|BR|IN)$".into()),
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        // ════════════════════════════════════════════
        // CMS
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "Magento - admin".into(),
            description: "Protege el panel de administración de Magento".into(),
            category: "cms".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(admin|index\.php/admin)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Magento - API".into(),
            description: "Protege la API REST de Magento contra abusos".into(),
            category: "cms".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/rest/".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(30),
            find_time_seconds: Some(300),
            ban_time_seconds: Some(1800),
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Magento - checkout".into(),
            description: "Rate limiting en checkout para prevenir scraping de precios".into(),
            category: "cms".into(),
            severity: "🟡 Medio".into(),
            path: Some(r"^/(checkout|onepage|checkout/cart)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(20),
            find_time_seconds: Some(300),
            ban_time_seconds: Some(1800),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4],
            bantime_maxtime_seconds: 86400,
            ban_count_decay_days: 14,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "PrestaShop - admin".into(),
            description: "Protege el panel de administración de PrestaShop".into(),
            category: "cms".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(admin|admin[0-9]+|administration)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "PrestaShop - install".into(),
            description: "Bloquea el instalador de PrestaShop (debe eliminarse tras instalar)".into(),
            category: "cms".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/install/".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Nextcloud - login".into(),
            description: "Protege el login de Nextcloud contra fuerza bruta".into(),
            category: "cms".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(login|index\.php/login)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Nextcloud - shared links".into(),
            description: "Rate limiting para enlaces compartidos de Nextcloud".into(),
            category: "cms".into(),
            severity: "🟡 Medio".into(),
            path: Some(r"^/s/".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(30),
            find_time_seconds: Some(300),
            ban_time_seconds: Some(1800),
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 7,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "MediaWiki - api.php".into(),
            description: "Rate limiting para la API de MediaWiki".into(),
            category: "cms".into(),
            severity: "🟡 Medio".into(),
            path: Some(r"^/api\.php".into()),
            query: Some(r"action=(edit|delete|move|import|upload)".into()),
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(10),
            find_time_seconds: Some(300),
            ban_time_seconds: Some(1800),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4],
            bantime_maxtime_seconds: 86400,
            ban_count_decay_days: 14,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Ghost - admin".into(),
            description: "Protege el panel de administración de Ghost CMS".into(),
            category: "cms".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/(ghost|ghost/api|admin)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },

        // ════════════════════════════════════════════
        // Infraestructura
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "Grafana - login".into(),
            description: "Protege el login de Grafana contra fuerza bruta".into(),
            category: "infra".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(login|grafana/login)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Kibana - dashboard".into(),
            description: "Protege el dashboard de Kibana contra accesos no autorizados".into(),
            category: "infra".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(kibana|app/kibana)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Kubernetes Dashboard".into(),
            description: "Protege el dashboard de Kubernetes contra accesos".into(),
            category: "infra".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/api/v1/namespaces/kubernetes-dashboard".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Portainer - login".into(),
            description: "Protege el login de Portainer (gestión Docker)".into(),
            category: "infra".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/portainer/api/auth".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Traefik Dashboard".into(),
            description: "Protege el dashboard de Traefik (proxy inverso)".into(),
            category: "infra".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/(dashboard|api/http)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "pgAdmin - login".into(),
            description: "Protege pgAdmin (gestión PostgreSQL) contra accesos".into(),
            category: "infra".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(pgadmin|pgadmin4)/login".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "Home Assistant - login".into(),
            description: "Protege el login de Home Assistant".into(),
            category: "infra".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/(auth/login|api/auth)".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },

        // ════════════════════════════════════════════
        // Probes de seguridad
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "Log4j / Log4Shell".into(),
            description: "Detecta intentos de explotación de Log4j (CVE-2021-44228)".into(),
            category: "probes".into(),
            severity: "🔥 Crítico".into(),
            path: None,
            query: Some(r"\$\{|jndi:|\$\{jndi:(ldap|rmi|dns|http)".into()),
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "Docker socket exposure".into(),
            description: "Bloquea intentos de acceso al socket de Docker".into(),
            category: "probes".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"/(docker\.sock|var/run/docker\.sock)".into()),
            query: None,
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: false,
            max_retry: None,
            find_time_seconds: None,
            ban_time_seconds: None,
            bantime_increment: false,
            bantime_multipliers: vec![1],
            bantime_maxtime_seconds: 3600,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "AWS metadata endpoint".into(),
            description: "Bloquea intentos de SSRF al endpoint de metadatos de AWS".into(),
            category: "probes".into(),
            severity: "🔥 Crítico".into(),
            path: None,
            query: Some(r"169\.254\.169\.254|instance-data|imds".into()),
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(3),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "SSTI probes".into(),
            description: "Detecta intentos de Server-Side Template Injection".into(),
            category: "probes".into(),
            severity: "🔴 Alto".into(),
            path: None,
            query: Some(r"(\$\{[^}]+\}|\{\{[^}]+\}\}|#\{[^}]+\}|<%=|<%#)".into()),
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "Command injection probes".into(),
            description: "Detecta intentos de inyección de comandos en query params".into(),
            category: "probes".into(),
            severity: "🔴 Alto".into(),
            path: None,
            query: Some(r"(;\s*(id|whoami|cat|rm|wget|curl|bash|sh|nc)\b|\|\s*(id|whoami|cat|rm)\b|\$\(cat|\`cat)".into()),
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(86400),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: false,
        },
        RuleTemplate {
            name: "Open redirect probes".into(),
            description: "Detecta intentos de open redirect en parámetros de URL".into(),
            category: "probes".into(),
            severity: "🟡 Medio".into(),
            path: None,
            query: Some(r"(redirect|return|next|url|to|dest|target|goto)=https?://".into()),
            country_code: None,
            allow: false,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(10),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4],
            bantime_maxtime_seconds: 86400,
            ban_count_decay_days: 14,
            requires_fqdn: false,
        },

        // ════════════════════════════════════════════
        // Webmail
        // ════════════════════════════════════════════
        RuleTemplate {
            name: "Roundcube - login".into(),
            description: "Protege el login de Roundcube webmail contra fuerza bruta".into(),
            category: "webmail".into(),
            severity: "🔥 Crítico".into(),
            path: Some(r"^/(roundcube|webmail|mail)/".into()),
            query: Some(r"_task=login".into()),
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },
        RuleTemplate {
            name: "RainLoop / SnappyMail login".into(),
            description: "Protege el login de RainLoop o SnappyMail".into(),
            category: "webmail".into(),
            severity: "🔴 Alto".into(),
            path: Some(r"^/(rainloop|snappymail)/".into()),
            query: None,
            country_code: None,
            allow: true,
            store: true,
            rate_limit_enabled: true,
            max_retry: Some(5),
            find_time_seconds: Some(600),
            ban_time_seconds: Some(3600),
            bantime_increment: true,
            bantime_multipliers: vec![1, 2, 4, 8],
            bantime_maxtime_seconds: 604800,
            ban_count_decay_days: 30,
            requires_fqdn: true,
        },

        // ════════════════════════════════════════════
        // Fin de plantillas
        // ════════════════════════════════════════════
    ]
}
