use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct RuleTemplate {
    pub name: String,
    pub description: String,
    pub category: String,
    pub severity: String,
    pub ip_address: Option<String>,
    pub protocol: Option<String>,
    pub fqdn: Option<String>,
    pub path: Option<String>,
    pub query: Option<String>,
    pub city_name: Option<String>,
    pub country_name: Option<String>,
    pub country_code: Option<String>,
    pub user_agent: Option<String>,
    pub method: Option<String>,
    pub referer: Option<String>,
    pub content_type: Option<String>,
    pub accept_language: Option<String>,
    pub x_request_id: Option<String>,
    pub allow: bool,
    pub pipeline: String,
    pub rate_limit_profile_id: Option<i32>,
    pub rate_limit_profile_name: Option<String>,
    pub requires_fqdn: bool,
    pub must_have: bool,
    pub weight: i32,
}

#[derive(Debug, Clone, Serialize)]
pub struct RateLimitProfileTemplate {
    pub id: i32,
    pub name: String,
    pub description: String,
    pub max_requests: i32,
    pub window_seconds: i32,
    pub ban_seconds: i32,
    pub escalation_enabled: bool,
    pub escalation_multipliers: Vec<i32>,
    pub max_ban_seconds: i32,
    pub cooldown_seconds: i32,
    pub fail_codes: Vec<i32>,
}

pub fn all_rule_templates() -> Vec<RuleTemplate> {
    vec![
        // ═══════════════════════════════════════════════════════════════
        //  WAF TEMPLATES (pipeline = "waf", no rate limit profile)
        // ═══════════════════════════════════════════════════════════════
        //
        // Template 1 — WordPress wp-content uploads
        RuleTemplate {
            name: "WordPress - wp-content uploads".into(),
            description: "Bloquea ejecución de scripts en directorio de uploads".into(),
            category: "wordpress".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/wp-content/uploads/.*\.(php|phtml|php5)$".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 2 — Drupal install.php
        RuleTemplate {
            name: "Drupal - install.php".into(),
            description: "Bloquea el instalador de Drupal (debe eliminarse tras instalar)".into(),
            category: "drupal".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/install\.php".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 3 — Laravel debug bar
        RuleTemplate {
            name: "Laravel - debug bar".into(),
            description: "Bloquea la barra de depuración de Laravel en producción".into(),
            category: "laravel".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/_debugbar".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 4 — Laravel Telescope
        RuleTemplate {
            name: "Laravel - Telescope".into(),
            description: "Bloquea Laravel Telescope en producción".into(),
            category: "laravel".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/telescope".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 5 — Adminer
        RuleTemplate {
            name: "Adminer".into(),
            description: "Bloquea Adminer (herramienta de gestión BD)".into(),
            category: "paneles".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(adminer|adminer-)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },
        // Template 6 — API GraphQL introspection
        RuleTemplate {
            name: "API - GraphQL introspection".into(),
            description: "Bloquea consultas de introspection de GraphQL en producción".into(),
            category: "api".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(graphql|api/graphql)".into()),
            query: Some(r"(introspection|__schema|__type|__typename)".into()),
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },
        // Template 7 — Git .git exposure
        RuleTemplate {
            name: "Git - .git exposure".into(),
            description: "Bloquea exposición del directorio .git".into(),
            category: "servidores".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/\.git".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: true,
            weight: 10,
        },
        // Template 8 — Archivos sensibles
        RuleTemplate {
            name: "Archivos sensibles".into(),
            description: "Bloquea acceso a archivos de configuración y backups".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"\.(env|bak|sql|dump|config|yml|yaml|json|log|ini)$".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 100,
        },
        // Template 9 — Directorios de sistema
        RuleTemplate {
            name: "Directorios de sistema".into(),
            description: "Bloquea acceso a directorios internos del proyecto".into(),
            category: "seguridad".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(vendor|node_modules|storage|cache|logs|tmp|\.git|\.env)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 10,
        },
        // Template 10 — phpinfo exposure
        RuleTemplate {
            name: "phpinfo exposure".into(),
            description: "Bloquea phpinfo() que expone configuración del servidor".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"(phpinfo|info\.php)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 100,
        },
        // Template 11 — User-Agent bots conocidos
        RuleTemplate {
            name: "User-Agent bots conocidos".into(),
            description: "Bloquea user-agents de bots maliciosos conocidos".into(),
            category: "bots".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: Some(r"(?i)(curl|wget|python-requests|go-http-client|Java/|libwww|phpcrawl|nikto|nessus|nmap|openvas|masscan|zgrab|sqlmap|havij|wpscan|acunetix|burp|hydra|metasploit|gobuster|dirbuster|wfuzz|WhatWeb|recon-ng|theharvester)".into()),
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 200,
        },
        // Template 12 — Bloquear países sin negocio
        RuleTemplate {
            name: "Bloquear países sin negocio".into(),
            description: "Deniega tráfico de países donde no operas".into(),
            category: "geo".into(),
            severity: "🟢 Bajo".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: None,
            city_name: None,
            country_name: None,
            country_code: Some(r"^(RU|CN|KP|IR|BY|AF|SY|VE|CU|SD)$".into()),
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: false,
            weight: 300,
        },
        // Template 13 — Bloquear tráfico hosting/VPS
        RuleTemplate {
            name: "Bloquear tráfico hosting/VPS".into(),
            description: "Bloquea países con alta concentración de tráfico malicioso en hosting".into(),
            category: "geo".into(),
            severity: "🟢 Bajo".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: None,
            city_name: None,
            country_name: None,
            country_code: Some(r"^(RU|CN|NL|DE|SG|HK|UA)$".into()),
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: false,
            weight: 300,
        },
        // Template 14 — PrestaShop install
        RuleTemplate {
            name: "PrestaShop - install".into(),
            description: "Bloquea el instalador de PrestaShop (debe eliminarse tras instalar)".into(),
            category: "cms".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/install/".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 15 — Docker socket exposure
        RuleTemplate {
            name: "Docker socket exposure".into(),
            description: "Bloquea intentos de acceso al socket de Docker".into(),
            category: "probes".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"/(docker\.sock|var/run/docker\.sock)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 10,
        },
        // Template 16 — SSTI probes
        RuleTemplate {
            name: "SSTI probes".into(),
            description: "Detecta intentos de Server-Side Template Injection".into(),
            category: "probes".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: Some(r"(?i)(\{\{.*\}\}|<\%.*\%>|\$\(.*\)|\$\{.*\}|#\{.*\}|#exec|#print|#include|template.*injection|freemarker|velocity|thymeleaf|handlebars|mustache)".into()),
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: false,
            weight: 100,
        },
        // Template 17 — SQL injection probes (MOVED from Jail to WAF)
        RuleTemplate {
            name: "SQL injection probes".into(),
            description: "Detecta patrones comunes de SQL injection en query params".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: Some(r"(?i)(union\s+select|select\s+from|insert\s+into|drop\s+table|delete\s+from|alter\s+table|create\s+table|\bexec\b\s*sp_|\bexec\b\s*xp_|pg_sleep|waitfor\s+delay|benchmark\(|sleep\s*\(|--|#|\bOR\b\s+\d+=\d+|\bAND\b\s+\d+=\d+)".into()),
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 100,
        },
        // Template 18 — XSS probes (MOVED from Jail to WAF)
        RuleTemplate {
            name: "XSS probes".into(),
            description: "Detecta patrones comunes de Cross-Site Scripting en query params".into(),
            category: "seguridad".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: Some(r"(?i)(<script|<img\s+.*onerror|<svg\s+.*onload|onerror=|onload=|onclick=|onmouseover=|javascript:\s*$|alert\(|prompt\(|confirm\(|document\.cookie|document\.location|fromCharCode|eval\(|String\.fromCharCode|<iframe|<embed|<object)".into()),
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 200,
        },
        // Template 19 — Command injection probes (MOVED from Jail to WAF)
        RuleTemplate {
            name: "Command injection probes".into(),
            description: "Detecta intentos de inyección de comandos en query params".into(),
            category: "probes".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: Some(r"(?i)([|;&]\s*(cat|wget|curl|bash|sh|python|perl|ruby|nc|nmap|which|whoami|id|uname|ls\s+-la|rm\s+-rf|chmod|chown|sudo|passwd|/etc/passwd|/etc/shadow)|\$\(|\`.*\`|%0a|%0d|%00)".into()),
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 100,
        },
        // Template 20 — Open redirect probes (MOVED from Jail to WAF)
        RuleTemplate {
            name: "Open redirect probes".into(),
            description: "Detecta intentos de open redirect en parámetros de URL".into(),
            category: "probes".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: Some(r"(?i)(redirect_uri=|return_url=|return_path=|next=|callback=|goto=|url=|target=|destination=|continue=|to_url=|redirect=|redir=|r=)".into()),
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: false,
            weight: 200,
        },
        // Template 21 — Log4j / Log4Shell (MOVED from Jail to WAF)
        RuleTemplate {
            name: "Log4j / Log4Shell".into(),
            description: "Detecta intentos de explotación de Log4j (CVE-2021-44228)".into(),
            category: "probes".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: Some(r"(?i)(\$\{jndi:|\$\{log4j:|\$\{lower:|\$\{env:|\$\{sys:|\$\{base64:|\$\{::-})".into()),
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 10,
        },
        // Template 22 — Path traversal probes (MOVED from Jail to WAF)
        RuleTemplate {
            name: "Path traversal probes".into(),
            description: "Detecta intentos de path traversal (../)".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"\.\./".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 100,
        },
        // Template 23 — User-Agent vacío (NEW)
        RuleTemplate {
            name: "User-Agent vacío".into(),
            description: "Bloquea peticiones sin User-Agent (bots/scripts)".into(),
            category: "bots".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: Some(r"^$".into()),
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 200,
        },
        // Template 24 — Swagger / API docs (NEW)
        RuleTemplate {
            name: "Swagger / API docs".into(),
            description: "Bloquea documentación interactiva de API en producción".into(),
            category: "api".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(swagger|api/docs|openapi|redoc|api/swagger)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },
        // Template 25 — Laravel Ignition (NEW)
        RuleTemplate {
            name: "Laravel - Ignition".into(),
            description: "Bloquea Ignition (depurador de errores de Laravel) en producción".into(),
            category: "laravel".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/_ignition".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 26 — Symfony _profiler (NEW)
        RuleTemplate {
            name: "Symfony - _profiler".into(),
            description: "Bloquea el profiler de Symfony en producción".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/_profiler".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 27 — Symfony _wdt (NEW)
        RuleTemplate {
            name: "Symfony - _wdt".into(),
            description: "Bloquea el Web Debug Toolbar de Symfony en producción".into(),
            category: "seguridad".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/_wdt".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },
        // Template 28 — Claves SSH/GPG (NEW)
        RuleTemplate {
            name: "Claves SSH/GPG".into(),
            description: "Bloquea exposición de claves privadas SSH, GPG y certificados".into(),
            category: "seguridad".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"\.(pem|key|ppk|asc|gpg)$".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 10,
        },
        // Template 29 — Archivos de sistema (NEW)
        RuleTemplate {
            name: "Archivos de sistema".into(),
            description: "Bloquea archivos de sistema y editor (DS_Store, thumbs.db, .swp)".into(),
            category: "seguridad".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"(\.DS_Store|desktop\.ini|thumbs\.db|\.swp|\.swo)$".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 200,
        },
        // Template 30 — Apache/Nginx status (NEW)
        RuleTemplate {
            name: "Apache/Nginx status".into(),
            description: "Bloquea páginas de estado de servidores web".into(),
            category: "servidores".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(server-status|server-info|nginx_status|fpm-status|fpm-ping)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: true,
            weight: 100,
        },
        // Template 31 — Mailpit / Mailhog (NEW)
        RuleTemplate {
            name: "Mailpit / Mailhog".into(),
            description: "Bloquea herramientas de captura de correo en desarrollo".into(),
            category: "servidores".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(mailpit|mailhog|mailcatcher)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },
        // Template 32 — API admin endpoints (NEW)
        RuleTemplate {
            name: "API - admin endpoints".into(),
            description: "Bloquea endpoints administrativos de API".into(),
            category: "api".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(api/v1/admin|admin/api)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 33 — README / changelog (NEW)
        RuleTemplate {
            name: "README / changelog".into(),
            description: "Bloquea exposición de archivos de documentación del proyecto".into(),
            category: "seguridad".into(),
            severity: "🟢 Bajo".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(README|CHANGELOG|CONTRIBUTING|LICENSE)\.(md|txt)$".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: false,
            weight: 300,
        },
        // Template 34 — composer.json / package.json (NEW)
        RuleTemplate {
            name: "composer.json / package.json".into(),
            description: "Bloquea exposición de manifiestos de dependencias".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(composer\.json|package\.json|yarn\.lock|package-lock\.json)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: false,
            must_have: true,
            weight: 100,
        },
        // Template 35 — phpMyAdmin variants (NEW)
        RuleTemplate {
            name: "phpMyAdmin variants".into(),
            description: "Bloquea variantes de phpMyAdmin con sufijos numéricos".into(),
            category: "paneles".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(phpmyadmin[0-9]*|pma[0-9]*|mysql[0-9]*|phpPgAdmin|sqldb|sqladmin)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "waf".into(),
            rate_limit_profile_id: None,
            rate_limit_profile_name: None,
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },

        // ═══════════════════════════════════════════════════════════════
        //  JAIL TEMPLATES — Profile 1 (Auth Brute Force)
        // ═══════════════════════════════════════════════════════════════
        // Template 36
        RuleTemplate {
            name: "WordPress - wp-login".into(),
            description: "Protege el login de WordPress contra fuerza bruta".into(),
            category: "wordpress".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/wp-login\.php".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 37
        RuleTemplate {
            name: "WordPress - wp-admin".into(),
            description: "Protege el panel de administración de WordPress".into(),
            category: "wordpress".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/wp-admin".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 38
        RuleTemplate {
            name: "Joomla - administrator".into(),
            description: "Protege el panel de administración de Joomla".into(),
            category: "joomla".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/administrator/".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 39
        RuleTemplate {
            name: "Joomla - com_user".into(),
            description: "Protege el componente de usuarios de Joomla".into(),
            category: "joomla".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/index\.php\?option=com_users".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 40
        RuleTemplate {
            name: "Drupal - user login".into(),
            description: "Protege el login de Drupal contra fuerza bruta".into(),
            category: "drupal".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(user|users?/login)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 41
        RuleTemplate {
            name: "API - login endpoint".into(),
            description: "Protege endpoints de autenticación contra fuerza bruta".into(),
            category: "api".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(api|auth)/(login|signin|token)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 42
        RuleTemplate {
            name: "Magento - admin".into(),
            description: "Protege el panel de administración de Magento".into(),
            category: "cms".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(admin|index\.php/admin)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 43
        RuleTemplate {
            name: "PrestaShop - admin".into(),
            description: "Protege el panel de administración de PrestaShop".into(),
            category: "cms".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(admin|admin[0-9]+|administration)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 44
        RuleTemplate {
            name: "Nextcloud - login".into(),
            description: "Protege el login de Nextcloud contra fuerza bruta".into(),
            category: "cms".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(login|index\.php/login)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 45
        RuleTemplate {
            name: "Ghost - admin".into(),
            description: "Protege el panel de administración de Ghost CMS".into(),
            category: "cms".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(ghost|ghost/api|admin)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 46
        RuleTemplate {
            name: "Grafana - login".into(),
            description: "Protege el login de Grafana contra fuerza bruta".into(),
            category: "infra".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(login|grafana/login)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 47
        RuleTemplate {
            name: "Kibana - dashboard".into(),
            description: "Protege el dashboard de Kibana contra accesos no autorizados".into(),
            category: "infra".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(kibana|app/kibana)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 48
        RuleTemplate {
            name: "Traefik Dashboard".into(),
            description: "Protege el dashboard de Traefik (proxy inverso)".into(),
            category: "infra".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(dashboard|api/http)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 49
        RuleTemplate {
            name: "Home Assistant - login".into(),
            description: "Protege el login de Home Assistant".into(),
            category: "infra".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(auth/login|api/auth)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 50
        RuleTemplate {
            name: "Roundcube - login".into(),
            description: "Protege el login de Roundcube webmail contra fuerza bruta".into(),
            category: "webmail".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(roundcube|webmail|mail)/".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 51
        RuleTemplate {
            name: "RainLoop / SnappyMail login".into(),
            description: "Protege el login de RainLoop o SnappyMail".into(),
            category: "webmail".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(rainloop|snappymail)/".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(1),
            rate_limit_profile_name: Some("Auth Brute Force".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },

        // ═══════════════════════════════════════════════════════════════
        //  JAIL TEMPLATES — Profile 2 (Admin Guard)
        // ═══════════════════════════════════════════════════════════════
        // Template 52
        RuleTemplate {
            name: "WordPress - xmlrpc".into(),
            description: "xmlrpc.php es vector clásico de fuerza bruta y DDoS".into(),
            category: "wordpress".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/xmlrpc\.php".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 53
        RuleTemplate {
            name: "phpMyAdmin - login".into(),
            description: "Protege phpMyAdmin contra accesos no autorizados".into(),
            category: "paneles".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(phpmyadmin|pma|mysql|phpPgAdmin)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 54
        RuleTemplate {
            name: "cPanel / WHM".into(),
            description: "Protege cPanel y Web Host Manager contra accesos".into(),
            category: "paneles".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(cpanel|whm|webmail|:2083|:2087)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 55
        RuleTemplate {
            name: "Webmin / Usermin".into(),
            description: "Protege paneles Webmin y Usermin".into(),
            category: "paneles".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(webmin|usermin)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 56
        RuleTemplate {
            name: "API - register endpoint".into(),
            description: "Protege registros contra bots".into(),
            category: "api".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(api|auth)/(register|signup)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 57
        RuleTemplate {
            name: "API - password reset".into(),
            description: "Protege endpoints de recuperación de contraseña".into(),
            category: "api".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(api|auth)/(reset|forgot|recover)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 58
        RuleTemplate {
            name: "Tomcat - manager".into(),
            description: "Protege el panel de gestión de Apache Tomcat".into(),
            category: "servidores".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(manager|host-manager)/".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 59
        RuleTemplate {
            name: "Jenkins - login".into(),
            description: "Protege Jenkins contra fuerza bruta".into(),
            category: "servidores".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(jenkins|ci)/".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 60
        RuleTemplate {
            name: "Kubernetes Dashboard".into(),
            description: "Protege el dashboard de Kubernetes contra accesos".into(),
            category: "infra".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/api/v1/namespaces/kubernetes-dashboard".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 61
        RuleTemplate {
            name: "Portainer - login".into(),
            description: "Protege el login de Portainer (gestión Docker)".into(),
            category: "infra".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/portainer/api/auth".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },
        // Template 62
        RuleTemplate {
            name: "pgAdmin - login".into(),
            description: "Protege pgAdmin (gestión PostgreSQL) contra accesos".into(),
            category: "infra".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(pgadmin|pgadmin4)/login".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 50,
        },

        // ═══════════════════════════════════════════════════════════════
        //  JAIL TEMPLATES — Profile 4 (API Abuse)
        // ═══════════════════════════════════════════════════════════════
        // Template 63
        RuleTemplate {
            name: "WordPress - REST API".into(),
            description: "Protege la API REST de WordPress contra abusos".into(),
            category: "wordpress".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/wp-json/".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(4),
            rate_limit_profile_name: Some("API Abuse".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },
        // Template 64
        RuleTemplate {
            name: "Magento - API".into(),
            description: "Protege la API REST de Magento contra abusos".into(),
            category: "cms".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/rest/".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(4),
            rate_limit_profile_name: Some("API Abuse".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 65
        RuleTemplate {
            name: "Magento - checkout".into(),
            description: "Rate limiting en checkout para prevenir scraping de precios".into(),
            category: "cms".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(checkout|onepage|checkout/cart)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(4),
            rate_limit_profile_name: Some("API Abuse".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },
        // Template 66
        RuleTemplate {
            name: "Nextcloud - shared links".into(),
            description: "Rate limiting para enlaces compartidos de Nextcloud".into(),
            category: "cms".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/s/".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(4),
            rate_limit_profile_name: Some("API Abuse".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },
        // Template 67
        RuleTemplate {
            name: "MediaWiki - api.php".into(),
            description: "Rate limiting para la API de MediaWiki".into(),
            category: "cms".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/api\.php".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(4),
            rate_limit_profile_name: Some("API Abuse".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },

        // ═══════════════════════════════════════════════════════════════
        //  JAIL TEMPLATES — Profile 5 (Scraping)
        // ═══════════════════════════════════════════════════════════════
        // Template 68
        RuleTemplate {
            name: "Rate limit - scraping".into(),
            description: "Rate limiting agresivo para prevenir scraping masivo".into(),
            category: "bots".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: None,
            city_name: None,
            country_name: None,
            country_code: Some(r"^(RU|CN|NL|DE|SG|HK)$".into()),
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(5),
            rate_limit_profile_name: Some("Scraping".into()),
            requires_fqdn: false,
            must_have: false,
            weight: 200,
        },

        // ═══════════════════════════════════════════════════════════════
        //  NEW JAIL TEMPLATES
        // ═══════════════════════════════════════════════════════════════
        // Template 69 — Search endpoint abuse
        RuleTemplate {
            name: "Search endpoint abuse".into(),
            description: "Rate limiting en endpoints de búsqueda para prevenir abusos".into(),
            category: "api".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(search|api/search|s/|api/s)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(4),
            rate_limit_profile_name: Some("API Abuse".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },
        // Template 70 — Comment / form spam
        RuleTemplate {
            name: "Comment / form spam".into(),
            description: "Rate limiting en formularios de comentarios contra spam".into(),
            category: "bots".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(wp-comments-post|comment|comments/ajax)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: Some(r"(?i)^POST$".into()),
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(5),
            rate_limit_profile_name: Some("Scraping".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },
        // Template 71 — File upload abuse
        RuleTemplate {
            name: "File upload abuse".into(),
            description: "Rate limiting en endpoints de subida de archivos".into(),
            category: "seguridad".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(upload|file-upload|api/upload|wp-content/uploads)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 72 — PHPUnit probe (RCE)
        RuleTemplate {
            name: "PHPUnit probe (RCE)".into(),
            description: "Detecta intentos de explotación de PHPUnit (CVE-2017-9841)".into(),
            category: "probes".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/vendor/phpunit".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: false,
            must_have: true,
            weight: 10,
        },
        // Template 73 — Drupal xmlrpc
        RuleTemplate {
            name: "Drupal - xmlrpc".into(),
            description: "Protege xmlrpc.php de Drupal contra fuerza bruta".into(),
            category: "drupal".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/xmlrpc\.php".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: false,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 74 — GraphQL abuse
        RuleTemplate {
            name: "GraphQL abuse".into(),
            description: "Rate limiting para endpoints GraphQL contra abusos".into(),
            category: "api".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(graphql|api/graphql)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(4),
            rate_limit_profile_name: Some("API Abuse".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 200,
        },
        // Template 75 — OAuth2 callback abuse
        RuleTemplate {
            name: "OAuth2 callback abuse".into(),
            description: "Protege callbacks OAuth2 contra fuerza bruta y replay".into(),
            category: "api".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(oauth|auth/callback|api/oauth)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(2),
            rate_limit_profile_name: Some("Admin Guard".into()),
            requires_fqdn: true,
            must_have: false,
            weight: 100,
        },
        // Template 76 — Scanner de directorios comunes
        RuleTemplate {
            name: "Scanner - directorios comunes".into(),
            description: "Rate limiting para escáneres que prueban directorios comunes (admin, backup, tmp, test, dev)".into(),
            category: "probes".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(admin|administrator|backup|backups|tmp|temp|test|tests|dev|development|private|restrito|old|new)(/|$)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(3),
            rate_limit_profile_name: Some("Path Scanning".into()),
            requires_fqdn: false,
            must_have: true,
            weight: 10,
        },
        // Template 77 — Scanner de archivos de configuración
        RuleTemplate {
            name: "Scanner - archivos de configuración".into(),
            description: "Rate limiting para escáneres que buscan archivos de configuración y backups".into(),
            category: "probes".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"\.(env|bak|sql|dump|config|yml|yaml|json|log|ini)$|/(wp-config|configuration\.php|settings|database\.yml)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(3),
            rate_limit_profile_name: Some("Path Scanning".into()),
            requires_fqdn: false,
            must_have: true,
            weight: 10,
        },
        // Template 78 — Scanner de paneles de control
        RuleTemplate {
            name: "Scanner - paneles de control".into(),
            description: "Rate limiting para escáneres que buscan paneles de administración y phpMyAdmin".into(),
            category: "probes".into(),
            severity: "🔴 Alto".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"^/(panel|cpanel|plesk|webmin|vestacp|kloxo|directadmin|phpmyadmin|pma|myadmin|mysql|phpPgAdmin|pgadmin)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(3),
            rate_limit_profile_name: Some("Path Scanning".into()),
            requires_fqdn: false,
            must_have: true,
            weight: 10,
        },
        // Template 79 — Scanner de vulnerabilidades web
        RuleTemplate {
            name: "Scanner - vulnerabilidades web".into(),
            description: "Rate limiting para escáneres que buscan shells, backdoors y exploits conocidos".into(),
            category: "probes".into(),
            severity: "🔥 Crítico".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: Some(r"(shell|cmd|rce|webshell|backdoor|hack|exploit|cve-\d{4}|payload|eval|exec|server-status|server-info|info\.php|phpinfo)".into()),
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(9),
            rate_limit_profile_name: Some("Scanner Aggressive".into()),
            requires_fqdn: false,
            must_have: true,
            weight: 10,
        },
        // Template 80 — Global Shield catch-all
        RuleTemplate {
            name: "Global Shield catch-all".into(),
            description: "Rate limiting global: cualquier IP que genere demasiados errores en 60s será rate-limitada".into(),
            category: "bots".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(8),
            rate_limit_profile_name: Some("Global Shield".into()),
            requires_fqdn: false,
            must_have: false,
            weight: 9999,
        },
        // Template 81 — Scanner genérico (404 catch-all)
        RuleTemplate {
            name: "Scanner genérico (404 catch-all)".into(),
            description: "Rate limiting global basado en 404: cualquier IP que genere demasiados errores 404 será limitada. Sin filtro de path, must_have: true".into(),
            category: "probes".into(),
            severity: "🟡 Medio".into(),
            ip_address: None,
            protocol: None,
            fqdn: None,
            path: None,
            query: None,
            city_name: None,
            country_name: None,
            country_code: None,
            user_agent: None,
            method: None,
            referer: None,
            content_type: None,
            accept_language: None,
            x_request_id: None,
            allow: true,
            pipeline: "jail".into(),
            rate_limit_profile_id: Some(3),
            rate_limit_profile_name: Some("Path Scanning".into()),
            requires_fqdn: false,
            must_have: true,
            weight: 9998,
        },
    ]
}

pub fn all_rate_limit_profile_templates() -> Vec<RateLimitProfileTemplate> {
    vec![
        RateLimitProfileTemplate {
            id: 1,
            name: "Auth Brute Force".into(),
            description: "5 requests in 5 minutes → 15min ban with escalation".into(),
            max_requests: 5,
            window_seconds: 300,
            ban_seconds: 900,
            escalation_enabled: true,
            escalation_multipliers: vec![1, 2, 4, 8],
            max_ban_seconds: 604800,
            cooldown_seconds: 30,
            fail_codes: vec![401],
        },
        RateLimitProfileTemplate {
            id: 2,
            name: "Admin Guard".into(),
            description: "5 requests in 5 minutes → 1h ban with escalation".into(),
            max_requests: 5,
            window_seconds: 300,
            ban_seconds: 3600,
            escalation_enabled: true,
            escalation_multipliers: vec![1, 2, 4, 8],
            max_ban_seconds: 604800,
            cooldown_seconds: 30,
            fail_codes: vec![401, 403],
        },
        RateLimitProfileTemplate {
            id: 3,
            name: "Path Scanning".into(),
            description: "20 requests in 60 seconds → 5min ban with escalation. Un humano jamás genera 20 errores 404 en 1 minuto.".into(),
            max_requests: 20,
            window_seconds: 60,
            ban_seconds: 300,
            escalation_enabled: true,
            escalation_multipliers: vec![1, 2, 4, 8],
            max_ban_seconds: 86400,
            cooldown_seconds: 30,
            fail_codes: vec![403, 404],
        },
        RateLimitProfileTemplate {
            id: 4,
            name: "API Abuse".into(),
            description: "100 requests in 1 minute → 5min ban with escalation".into(),
            max_requests: 100,
            window_seconds: 60,
            ban_seconds: 300,
            escalation_enabled: true,
            escalation_multipliers: vec![1, 2, 4, 8],
            max_ban_seconds: 86400,
            cooldown_seconds: 30,
            fail_codes: vec![401, 403, 429],
        },
        RateLimitProfileTemplate {
            id: 5,
            name: "Scraping".into(),
            description: "60 requests in 1 minute → 5min ban with escalation".into(),
            max_requests: 60,
            window_seconds: 60,
            ban_seconds: 300,
            escalation_enabled: true,
            escalation_multipliers: vec![1, 2, 4, 8],
            max_ban_seconds: 86400,
            cooldown_seconds: 7,
            fail_codes: vec![403, 429, 500],
        },
        RateLimitProfileTemplate {
            id: 6,
            name: "Health & Webhooks".into(),
            description: "100 requests in 60 seconds → 1min ban".into(),
            max_requests: 100,
            window_seconds: 60,
            ban_seconds: 60,
            escalation_enabled: false,
            escalation_multipliers: vec![1],
            max_ban_seconds: 60,
            cooldown_seconds: 30,
            fail_codes: vec![500, 502, 503],
        },
        RateLimitProfileTemplate {
            id: 7,
            name: "Recidive".into(),
            description: "3 reincidences in 48h → 7-day ban (max 30 days)".into(),
            max_requests: 3,
            window_seconds: 172800,
            ban_seconds: 604800,
            escalation_enabled: true,
            escalation_multipliers: vec![1, 2, 4, 8],
            max_ban_seconds: 2592000,
            cooldown_seconds: 60,
            fail_codes: vec![403, 429],
        },
        RateLimitProfileTemplate {
            id: 9,
            name: "Scanner Aggressive".into(),
            description: "50 requests in 10 seconds → 30min ban with escalation. Para escáneres rápidos incluso con retardo aleatorio.".into(),
            max_requests: 50,
            window_seconds: 10,
            ban_seconds: 1800,
            escalation_enabled: true,
            escalation_multipliers: vec![1, 2, 4, 8],
            max_ban_seconds: 604800,
            cooldown_seconds: 30,
            fail_codes: vec![403, 404, 405, 500],
        },
        RateLimitProfileTemplate {
            id: 8,
            name: "Global Shield".into(),
            description: "Catch-all: 300 errores en 60s → 5min ban with escalation. Sin filtros, matchea todo. Atrapa cualquier IP que genere demasiados errores.".into(),
            max_requests: 300,
            window_seconds: 60,
            ban_seconds: 300,
            escalation_enabled: true,
            escalation_multipliers: vec![1, 2, 4, 8],
            max_ban_seconds: 86400,
            cooldown_seconds: 30,
            fail_codes: vec![403, 404, 429, 500, 502, 503],
        },
    ]
}
